CREATE TABLE IF NOT EXISTS personas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    edad INTEGER NOT NULL,
    fecha DATE NOT NULL,
    tipo_persona VARCHAR(10) NOT NULL,
    dni VARCHAR(20) NOT NULL UNIQUE
);
