vaadin:
  launch-browser: true
spring:
  application:
    name: claude-ai
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      model: claude-3-sonnet-2024022
      max-tokens: 1024
      temperature: 0.7
      top-p: 0.9
      stop-sequences: [ "END"]
      system: "You are an AI assistant that provides helpful responses."
      streaming: false
